#!/bin/bash
# syncs the current project (as defined by git repo) to default EC2 instance

project_path=`git rev-parse --show-toplevel 2> /dev/null`

if [ $? -eq 0 ]; then
    project_name=`basename $project_path`
    # echo "in project $project_name"
    rsync -avL --progress -e "ssh" $1 $project_path ubuntu@$AWS_INSTANCE_URL:projects
fi
