#!/bin/bash

project_path=`git rev-parse --show-toplevel 2> /dev/null`

if [ $? -eq 0 ]; then
    project_name=`basename $project_path`
    # echo "in project $project_name"
    rsync -avL --progress -e "ssh" $1 ubuntu@$instanceUrl:projects/$project_name/ $project_path
fi

